services:
  - type: web
    name: chatApp
    env: node
    plan: free
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
